version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@4.0.0

jobs:
  build:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install dependencies
          command: pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: pnpm build
      - run:
          name: Start tests
          command: pnpm test

workflows:
  build_and_test:
    jobs:
      - build:
          name: build_and_test
          filters:
            branches:
              ignore:
                - master

  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          auth:
            - aws-cli/setup:
                aws-region: AWS_DEFAULT_REGION
                aws-access-key-id: AWS_ACCESS_KEY_ID
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "$CIRCLE_SHA1"
#      - aws-ecs/deploy-service-update:
#          requires:
#            - aws-ecr/build-and-push-image
#          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
#          cluster: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
#          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"