version: 2.1

jobs:
  build_and_test:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@8
      - run:
          name: Install
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
      - run:
          name: prettier
          command: pnpm run prettier:check
      - run:
          name: ESLint
          command: pnpm run lint

  chromatic-deployment:
    docker:
      - image: node:18
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@8
      - run:
          name: Install
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
      - run: pnpm run chromatic

workflows:
  production:
    jobs:
      - build_and_test
      - chromatic-deployment:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
